name: geopython-workshop
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pyproj
  - shapely
  - gdal
  - fiona
  - rasterio
  - geopandas
  - descartes
  - pygeometa
  - folium
  - owslib
  - bokeh
  - ipyleaflet
  - matplotlib
  - pip
  - pip:
    - pandas-bokeh
